version: '3'
services:

  # The core platform, mounts docker control socket and route definition into the image
  provider-core:
    image: fraunhoferaisec/trusted-connector-core:${EXAMPLE_TAG:-develop}
    tty: true
    stdin_open: true
    volumes:
      - ../log/:/root/log/
      - /var/run/docker.sock:/var/run/docker.sock
      - ../cert-stores/provider-keystore.p12:/root/etc/provider-keystore.p12
      - ../cert-stores/truststore.p12:/root/etc/truststore.p12
      - ./example-provider-routes.xml:/root/deploy/example-provider-routes.xml
      - ./farmer_data.csv:/root/deploy/farmer_data.csv
      - ./ai_tech_data.csv:/root/deploy/ai_tech_data.csv

    # Enable this lines for debugging or UI access from localhost
    ports:
      - 8989:8989
#      - "5005:5005"
#      - "8181:8181"
#      - "8443:8443"
    networks:
      - ids-wide
      - provider-internal

networks:
  ids-wide:
    driver: bridge
  provider-internal:
    driver: bridge
